language: node_js
sudo: true
node_js: 8
cache:
  directories:
    - node_modules
script:
- npm test
- npm run build
- npm install -g gulp
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8
- provider: script
  script: sh scripts/deploy-gh-pages.sh
  on:
    branch: master
    repo: watson-developer-cloud/react-components
  skip_cleanup: true
env:
  global:
  - secure: MBSrEaZhMrJPvxgzFv2tYWBEimAjwKRpwRfYEh6TtqE09xPqBgYQhOV6aRMRjHbL2QFdIgCcFJpJ9lYHS9qiyfaGOz+z+s/MtcMcuSx+7j4k7aO+UXrReT2hoGxC/N9IwT1ulE36LNff4Oh10LMYioGPClEsthzGh/jqEdguhzPsQNYEIpmUaPaxqY1y8ykDKohZ4mkruBwq0E9FJA0Dy0COtcmp+SmKS07tCQBcLdrgUdgg1e24+G6l2C5JuXDHEyIp23sJKIogjhtH2H1vPDqLOljMpKhDnQDSEsdEjW3fRLTgef7T4RxZCy1c2ZT18zUFpk6M+azro3D1QScyJo4dgPs0WzlNsja8HZZIlvyuVYhNn2ABmd3+r4rS9Rj+sM0oK7Ih79VuxqVsi3YA0TWW1rmlax3Szrh8Xk69OVsgQYiPn3za7Am4bsNEJmxGMUtlaQ+E/ySQMl5fx0R1dcmC3XjEUHPRLMdfARzNaz372CgjXzx2OihIRwGJlSgvfDs0zqpIg0VzEd0TgKv4wgq4A1kroA5rglPoiOysYTVZoG3SOEzKlXraeCC4FI0CullyGlnd1WUGm3r0hhJ5hbZyX4m/CTYoajPHaUk/nO6sNXcHu9koTO3iZI4BTt4j5hYuJ8PWD8dRVGzXTaQd6GCIwIKDB5nCpfPsYrOicZY=
  - secure: PERTaZVwz8w32MW8G+NiLt38KMFrYKk403JUwTDPjz8djLAtVzgUazDc8JWm0+36mmJVnTJnBNsuZvY6vmIWXTZQloEpSLcaCatugzPWV3GM4Q9sSdOhumwxct3GUrUmm76TpcF/vrzZhGLTDTPo5LF/VLjNL4bkB7PKApiN7OruOGbiHzk02HyYyx7+PaFcokCY6DHxLby7teNT/PjYGOgYHY2Su1jjMiZcxU2RkIKwhZXvb0t348h+2sylRi/CT/rgaszJCD4Ob1DTGqNhV8ViZydF3MYEMm4/DpNGwJQbHKehL0J271GPEdg09t/IYGsknKQf3zMIYMh3V+WhbeJA2BEOtttvaJd14FRjlZYSxImyDF0EqtGRzTOFqwRi8w6Sc4pE9UyQ3xuT4k0SB/NWjgouDyplkj8YqAzHyTaAEIi4wddQ5dAeeL89L4jwON/Y4isWe+LuVb0t4FkbgNv+XIQxF3oA7yknYQ7RuZp5YIwPjMb6u0Ar8oifUAVZ5JRxdqgWVrLjXnhbVZP6UBmoVeHjoAfGWyYEmQDt1NRHqviQDbY33gol/sqdYIZWiFYOJTXL7S1Ln3jVwn787k0YaRtkDGrMzvD4pYXXytSN16hSyGxlMZJZWgp0ZwS2uISePnsmbYCphcR64Q+v2bG12cN3Jzrd4Bry4z+MiHg=
